[package]
name = "crud-api"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = "1.42.1"
rust_decimal_macros = "1.40.0"
actix-web = "4.14.0"
sea-orm = {version="2.0.0", features=["sqlx-mysql", "runtime-tokio-rustls", "macros"]}
async-trait= "0.1.91"
serde = "1.0.229"
dotenvy = "0.15.7"
thiserror = "2.0.20"
